insert overwrite directory '/user/archer/output' select distinct(point_name) from tbl_cp_prop where (tbl_cp_prop.ref_cptype_code = 'CP-BUSSINESS-NONMAP-INDOOR' or tbl_cp_prop.ref_cptype_code = 'CP-BUSSINESS-NONMAP-OUTDOOR') and tbl_cp_prop.ref_cp_code not in (select tbl_cp_tag_relation.ref_cp_code from tbl_cp_tag_relation where tbl_cp_tag_relation.flag = 'BV2');

insert overwrite directory '/user/archer/output' select distinct(point_name) from tbl_cp_prop where (tbl_cp_prop.ref_cptype_code = 'CP-HOSPITAL-ROOM' or tbl_cp_prop.ref_cptype_code = 'CP-PRIVATE-HOSPITAL-ROOM') and tbl_cp_prop.ref_cp_code not in (select tbl_cp_tag_relation.ref_cp_code from tbl_cp_tag_relation where tbl_cp_tag_relation.flag = 'HV1.1' or tbl_cp_tag_relation.flag = 'PHV1.1' or tbl_cp_tag_relation.flag = 'PHV1.2');

-- super slow even with the map reduce
insert overwrite directory '/user/archer/output' select distinct(prop_value) from tbl_cp_prop join tbl_cp_exprop on tbl_cp_prop.ref_cp_code = tbl_cp_exprop.ref_cp_code where (tbl_cp_prop.ref_cptype_code = 'CP-HOSPITAL-ROOM' or tbl_cp_prop.ref_cptype_code = 'CP-PRIVATE-HOSPITAL-ROOM') and tbl_cp_prop.ref_cp_code not in (select tbl_cp_tag_relation.ref_cp_code from tbl_cp_tag_relation where tbl_cp_tag_relation.flag = 'HV1.1' or tbl_cp_tag_relation.flag = 'PHV1.1' or tbl_cp_tag_relation.flag = 'PHV1.2');

-- hive上导出家居建材的sell sell-out, tbl_cp_tag_relation的，且是审核通过de
insert overwrite directory '/user/archer/output' select distinct(e.prop_value) from tbl_cp_exprop e inner join tbl_cp_prop p on e.ref_cp_code = p.ref_cp_code inner join tbl_cp cp on cp.point_code = p.ref_cp_code inner join tbl_user_task_brief b on b.ref_area_code = cp.ref_area_code where (p.ref_cptype_code = 'CP-JIAJU-JIANCAI-JIADIAN-SELL' or p.ref_cptype_code = 'CP-JIAJU-JIANCAI-JIADIAN-SELL-OUT') and e.ref_exprop_code = 'EXP-CATEGORY' and p.ref_cp_code not in (select tbl_cp_tag_relation.ref_cp_code from tbl_cp_tag_relation where tbl_cp_tag_relation.flag = 'JIAJUV1') and (b.status_result = 1045 or b.status_result = 106 or b.status_result = 107);

-- hive上导出家居建材的sell sell-out, tbl_cp_tag_relation的，且是审核通过的prop_value
insert overwrite directory '/user/archer/output' select distinct(p.point_name) from tbl_cp_exprop e inner join tbl_cp_prop p on e.ref_cp_code = p.ref_cp_code inner join tbl_cp cp on cp.point_code = p.ref_cp_code inner join tbl_user_task_brief b on b.ref_area_code = cp.ref_area_code where (p.ref_cptype_code = 'CP-JIAJU-JIANCAI-JIADIAN-SELL' or p.ref_cptype_code = 'CP-JIAJU-JIANCAI-JIADIAN-SELL-OUT') and e.ref_exprop_code = 'EXP-CATEGORY' and p.ref_cp_code not in (select tbl_cp_tag_relation.ref_cp_code from tbl_cp_tag_relation where tbl_cp_tag_relation.flag = 'JIAJUV1') and (b.status_result = 1045 or b.status_result = 106 or b.status_result = 107);

-- hive上导出家居建材的sell sell-out, tbl_cp_tag_relation的，且是审核通过的point_name
insert overwrite directory '/user/archer/output' select distinct(p.point_name) from tbl_cp_prop p inner join tbl_cp cp on cp.point_code = p.ref_cp_code inner join tbl_user_task_brief b on b.ref_area_code = cp.ref_area_code where (p.ref_cptype_code = 'CP-JIAJU-JIANCAI-JIADIAN-SELL' or p.ref_cptype_code = 'CP-JIAJU-JIANCAI-JIADIAN-SELL-OUT') and p.ref_cp_code not in (select tbl_cp_tag_relation.ref_cp_code from tbl_cp_tag_relation where tbl_cp_tag_relation.flag = 'JIADIANV1' or tbl_cp_tag_relation.flag = 'JIADIANV2') and (b.status_result = 1045 or b.status_result = 106 or b.status_result = 107);

-- 找出家居建材的sell sell-out的审核的未清洗的点
select cp.point_name from tbl_cp p inner join tbl_cp_prop cp on p.point_code = cp.ref_cp_code inner join tbl_user_task_brief b on b.ref_area_code = p.ref_area_code where (cp.ref_cptype_code = 'CP-JIAJU-JIANCAI-JIADIAN-SELL' or cp.ref_cptype_code = 'CP-JIAJU-JIANCAI-JIADIAN-SELL-OUT') and (b.status_result = 1045 or b.status_result = 106 or b.status_result = 107) and (cp.ref_cp_code not in (select ref_cp_code from tbl_cp_tag_relation where flag = 'JIAJUV1' or flag = 'JIAJUV2'));

-- postgres 导出家居建材的sell sell-out的审核通过的，未能成功清洗的数据的去重的
\copy (select distinct(p.point_name) from tbl_cp_prop p inner join tbl_cp cp on cp.point_code = p.ref_cp_code inner join tbl_user_task_brief b on b.ref_area_code = cp.ref_area_code where (p.ref_cptype_code = 'CP-JIAJU-JIANCAI-JIADIAN-SELL' or p.ref_cptype_code = 'CP-JIAJU-JIANCAI-JIADIAN-SELL-OUT') and p.ref_cp_code not in (select tbl_cp_tag_relation.ref_cp_code from tbl_cp_tag_relation where tbl_cp_tag_relation.flag = 'JIAJUV1' or tbl_cp_tag_relation.flag = 'JIAJUV2' or tbl_cp_tag_relation.flag = 'JIAJUV3') and (b.status_result = 1045 or b.status_result = 106 or b.status_result = 107)) to '/tmp/jiajupointname.csv' delimiter ',' csv header;

insert overwrite directory '/user/archer/output' select distinct(point_name) from tbl_cp_prop where (tbl_cp_prop.ref_cptype_code = 'CP-BUSSINESS-NONMAP-INDOOR' or tbl_cp_prop.ref_cptype_code = 'CP-BUSSINESS-NONMAP-OUTDOOR') and tbl_cp_prop.ref_cp_code not in (select tbl_cp_tag.ref_cp_code from tbl_cp_tag);

-- 找出商场的INDOOR OUTDOOR且已经审核通过的数据
select count(distinct(p.point_code)) from tbl_cp p inner join tbl_cp_prop cp on p.point_code = cp.ref_cp_code inner join tbl_user_task_brief b on p.ref_area_code = b.ref_area_code where (cp.ref_cptype_code = 'CP-BUSSINESS-NONMAP-INDOOR' or cp.ref_cptype_code = 'CP-BUSSINESS-NONMAP-OUTDOOR') and (b.status_result = 1045 or b.status_result = 106 or b.status_result = 107);

-- 找出家居建材的SELL SELL-OUT的且已经审核通过的数据
select count(distinct(p.point_code)) from tbl_cp p inner join tbl_cp_prop cp on p.point_code = cp.ref_cp_code inner join tbl_user_task_brief b on p.ref_area_code = b.ref_area_code inner join tbl_cp_exprop e on e.ref_cp_code = p.point_code where (cp.ref_cptype_code = 'CP-JIAJU-JIANCAI-JIADIAN-SELL' or cp.ref_cptype_code = 'CP-JIAJU-JIANCAI-JIADIAN-SELL-OUT') and (b.status_result = 1045 or b.status_result = 106 or b.status_result = 107);
